acme_topic:
    channel: acme/channel
    handler:
        callback: 'acme.topic'

acme_rpc:
    channel: sample/{method}
    handler:
        callback: 'acme.rpc'
    requirements:
        method:
            pattern: "[a-z_]+"

product_topic:
    channel: product/channel
    handler:
        callback: 'product.topic'

product_rpc:
    channel: product/{method}
    handler:
        callback: 'product.rpc'
    requirements:
        method:
            pattern: "[a-z_]+"

cart_rpc:
    channel: cart/{method}
    handler:
        callback: 'cart.rpc'
    requirements:
        method:
            pattern: "[a-z_]+"

cart_topic:
    channel: cart/channel
    handler:
        callback: 'cart.topic'

user_rpc:
    channel: user/{method}
    handler:
        callback: 'user.rpc'
    requirements:
        method:
            pattern: "[a-z_]+"