acme_topic:
    channel: acme/channel
    handler:
        callback: 'acme.topic'

acme_rpc:
    channel: sample/{method}
    handler:
        callback: 'acme.rpc'
    requirements:
        method:
            pattern: "[a-z_]+"